export interface ServiceContactSeed {
  name: string
  email?: string
  address?: string
  category?: string
}

export const SERVICE_CONTACT_SEED: ServiceContactSeed[] = [
  { "name": "ACM Lebensversicherung AG", "email": "kontakt-acmd@acmd.de", "address": "Breite Straße 29, 40213 Düsseldorf, Deutschland" },
  { "name": "AGER Lebensversicherung AG", "email": "service@axa.de", "address": "Colonia-Allee 15, 51067 Köln, Deutschland" },
  { "name": "Aioi Nissay Dowa Life Insurance of Europe Aktiengesellschaft", "email": "kundenservice-life@aioinissaydowa.eu", "address": "Carl-Zeiss-Ring 25, 85737 Ismaning, Deutschland" },
  { "name": "Allianz Lebensversicherungs-Aktiengesellschaft", "email": "info@allianz.de", "address": "Heßbrühlstraße 2, 70565 Stuttgart, Deutschland" },
  { "name": "Alte Leipziger Lebensversicherung auf Gegenseitigkeit", "email": "service@alte-leipziger.de", "address": "Alte Leipziger-Platz 1, 61440 Oberursel, Deutschland" },
  { "name": "Athora Lebensversicherung Aktiengesellschaft", "email": "info.ge@athora.com", "address": "Söhnleinstraße 8, 65201 Wiesbaden, Deutschland" },
  { "name": "AXA Lebensversicherung Aktiengesellschaft", "email": "service@axa.de", "address": "Colonia Allee 10 - 20, 51067 Köln, Deutschland" },
  { "name": "Baloise Lebensversicherung Aktiengesellschaft Deutschland", "email": "info@baloise.de", "address": "Ludwig-Erhard-Straße 22, 20459 Hamburg, Deutschland" },
  { "name": "Bayern-Versicherung Lebensversicherung Aktiengesellschaft", "email": "service@vkb.de", "address": "Maximilianstraße 53, 80530 München, Deutschland" },
  { "name": "BL die Bayerische Lebensversicherung AG", "email": "info@diebayerische.de", "address": "Thomas-Dehler-Straße 25, 81737 München, Deutschland" },
  { "name": "BY die Bayerische Vorsorge Lebensversicherung a.G.", "email": "info@diebayerische.de", "address": "Thomas-Dehler-Straße 25, 81737 München, Deutschland" },
  { "name": "Concordia oeco Lebensversicherungs-AG", "email": "versicherungen@concordia.de", "address": "Karl-Wiechert-Allee 55, 30625 Hannover, Deutschland" },
  { "name": "Condor Lebensversicherungs-Aktiengesellschaft", "email": "kundenservice@condor-versicherungen.de", "address": "Heidenkampsweg 102, 20097 Hamburg, Deutschland" },
  { "name": "Continentale Lebensversicherung AG", "email": "info@continentale.de", "address": "Baierbrunner Straße 31-33, 81379 München, Deutschland" },
  { "name": "Cosmos Lebensversicherungs-Aktiengesellschaft", "email": "info@cosmosdirekt.de", "address": "Halbergstraße 50-60, 66121 Saarbrücken, Deutschland" },
  { "name": "Credit Life AG", "email": "service@creditlife.net", "address": "RheinLandplatz 1, 41460 Neuss, Deutschland" },
  { "name": "Debeka Lebensversicherungsverein auf Gegenseitigkeit Sitz Koblenz am Rhein", "email": "kundenservice@debeka.de", "address": "Debeka-Platz 1, 56073 Koblenz am Rhein, Deutschland" },
  { "name": "Delta Direkt Lebensversicherung Aktiengesellschaft München", "email": "info@deltadirekt.de", "address": "Ottostraße 16, 80333 München, Deutschland" },
  { "name": "Deutsche Lebensversicherungs-Aktiengesellschaft", "email": "info.dlvag@allianz.de", "address": "Merlitzstraße 8, 12489 Berlin, Deutschland" },
  { "name": "Deutsche Ärzteversicherung Aktiengesellschaft", "email": "service@aerzteversicherung.de", "address": "Colonia-Allee 10-20, 51067 Köln, Deutschland" },
  { "name": "DEVK Allgemeine Lebensversicherungs-Aktiengesellschaft", "email": "info@devk.de", "address": "Riehler Straße 190, 50735 Köln, Deutschland" },
  { "name": "DEVK Deutsche Eisenbahn Versicherung Lebensversicherungsverein a.G. Betriebliche Sozialeinrichtung der Deutschen Bahn", "email": "info@devk.de", "address": "Riehler Straße 190, 50735 Köln, Deutschland" },
  { "name": "Dialog Lebensversicherungs-Aktiengesellschaft", "email": "service@dialog-versicherung.de", "address": "Stadtberger Straße 99, 86157 Augsburg, Deutschland" },
  { "name": "DIREKTE LEBEN Versicherung AG", "email": "info@direkte-leben.de", "address": "Rotebühlstraße 120, 70197 Stuttgart, Deutschland" },
  { "name": "Dortmunder Lebensversicherung AG", "email": "info@die-dortmunder.de", "address": "Südwall 37-41, 44137 Dortmund, Deutschland" },
  { "name": "Entis Lebensversicherung AG", "email": "service@entis-lv.de", "address": "Dornhofstraße 36, 63263 Neu-Isenburg, Deutschland" },
  { "name": "ERGO Lebensversicherung Aktiengesellschaft", "email": "info@ergo.de", "address": "Überseering 45, 22297 Hamburg, Deutschland" },
  { "name": "ERGO Vorsorge Lebensversicherung Aktiengesellschaft", "email": "info@ergo-vorsorge.de", "address": "ERGO-Platz 1, 40477 Düsseldorf, Deutschland" },
  { "name": "EUROPA Lebensversicherung Aktiengesellschaft", "email": "info@continentale.de", "address": "Piusstraße 137, 50931 Köln, Deutschland" },
  { "name": "Frankfurt Münchener Lebensversicherung AG", "email": "anfrage.fml@flgruppe.de", "address": "Stahlgruberring 52, 81829 München, Deutschland" },
  { "name": "Frankfurter Lebensversicherung AG", "email": "anfrage.fl@flgruppe.de", "address": "Am Weidenring 56, 61352 Bad Homburg v.d. Höhe, Deutschland" },
  { "name": "Generali Deutschland Lebensversicherung AG", "email": "service@generali.de", "address": "Adenauerring 7, 81737 München, Deutschland" },
  { "name": "Gothaer Lebensversicherung Aktiengesellschaft", "email": "info@gothaer.de", "address": "Arnoldiplatz 1, 50969 Köln, Deutschland" },
  { "name": "Hannoversche Lebensversicherung AG", "email": "kontakt@hannoversche-leben.de", "address": "VHV-Platz 1, 30177 Hannover, Deutschland" },
  { "name": "Hallesche", "email": "service@hallesche.de", "address": "Löffelstraße 34-38, 70597 Stuttgart, Deutschland" },
  { "name": "HanseMerkur Lebensversicherung AG", "email": "info@hansemerkur.de", "address": "Siegfried-Wedells-Platz 1, 20354 Hamburg, Deutschland" },
  { "name": "HDI Lebensversicherung AG", "email": "leben.service@hdi.de", "address": "Charles-de-Gaulle-Platz 1, 50679 Köln, Deutschland" },
  { "name": "Heidelberger Lebensversicherung AG", "email": "service@heidelberger-leben.de", "address": "Dornhofstraße 36, 63263 Neu-Isenburg, Deutschland" },
  { "name": "HELVETIA schweizerische Lebensversicherungs-Aktiengesellschaft", "email": "info@helvetia.de", "address": "Weißadlergasse 2, 60311 Frankfurt am Main, Deutschland" },
  { "name": "HUK-COBURG-Lebensversicherung AG", "email": "Info@HUK-COBURG.de", "address": "Bahnhofsplatz, 96450 Coburg, Deutschland" },
  { "name": "IDEAL Lebensversicherung a.G.", "email": "info@ideal-versicherung.de", "address": "Kochstraße 26, 10969 Berlin, Deutschland" },
  { "name": "INTER Lebensversicherung AG", "email": "info@inter.de", "address": "Erzbergerstraße 9-15, 68165 Mannheim, Deutschland" },
  { "name": "InterRisk Lebensversicherungs-AG Vienna Insurance Group.", "email": "info@interrisk.de", "address": "Carl-Bosch-Straße 5, 65203 Wiesbaden, Deutschland" },
  { "name": "Itzehoer Lebensversicherungs-Aktiengesellschaft", "email": "info@itzehoer.de", "address": "Itzehoer Platz, 25521 Itzehoe, Deutschland" },
  { "name": "Lebensversicherung von 1871 auf Gegenseitigkeit München", "email": "info@lv1871.de", "address": "Maximiliansplatz 5, 80333 München, Deutschland" },
  { "name": "Lifestyle Protection Lebensversicherung AG", "email": "info@lifestyle-protection.net", "address": "Proactiv-Platz 1, 40721 Hilden, Deutschland" },
  { "name": "LPV Lebensversicherung AG", "email": "info@lifestyle-protection.com", "address": "ProActiv-Platz 1, 40721 Hilden, Deutschland" },
  { "name": "LVM Lebensversicherungs-AG", "email": "info@lvm.de", "address": "Kolde-Ring 21, 48151 Münster, Deutschland" },
  { "name": "Mecklenburgische Lebensversicherungs-Aktiengesellschaft", "email": "service@mecklenburgische.de", "address": "Platz der Mecklenburgischen 1, 30625 Hannover, Deutschland" },
  { "name": "myLife Lebensversicherung AG", "email": "info@mylife-leben.de", "address": "Herzberger Landstraße 25, 37085 Göttingen, Deutschland" },
  { "name": "MÜNCHENER VEREIN Lebensversicherung AG", "email": "info@muenchener-verein.de", "address": "Pettenkoferstraße 19, 80336 München, Deutschland" },
  { "name": "neue leben Lebensversicherung Aktiengesellschaft", "email": "info@neueleben.de", "address": "Hammerbrookstraße 69, 20097 Hamburg, Deutschland" },
  { "name": "NÜRNBERGER Lebensversicherung Aktiengesellschaft", "email": "info@nuernberger.de", "address": "Ostendstraße 100, 90482 Nürnberg, Deutschland" },
  { "name": "Protektor Lebensversicherungs-AG", "email": "contact@protektor-ag.de", "address": "Wilhelmstraße 43G, 10117 Berlin, Deutschland" },
  { "name": "Provinzial Lebensversicherung Aktiengesellschaft", "email": "service@provinzial.de", "address": "Sophienblatt 33, 24114 Kiel, Deutschland" },
  { "name": "Provinzial Lebensversicherung Hannover", "email": "service@vgh.de", "address": "Schiffgraben 4, 30159 Hannover, Deutschland" },
  { "name": "Proxalto Lebensversicherung Aktiengesellschaft c/o Viridium Group GmbH & Co. KG", "email": "service@proxalto-lv.de", "address": "Adenauerring 7, 81737 München, Deutschland" },
  { "name": "R + V Lebensversicherung a.G.", "email": "ruv@ruv.de", "address": "Wilhelmstraße 1, 65343 Eltville, Deutschland" },
  { "name": "R + V LEBENSVERSICHERUNG AKTIENGESELLSCHAFT", "email": "ruv@ruv.de", "address": "Raiffeisenplatz 1, 65189 Wiesbaden, Deutschland" },
  { "name": "SIGNAL IDUNA Lebensversicherung a. G.", "email": "info@signal-iduna.de", "address": "Neue Rabenstraße 15 - 19, 20354 Hamburg, Deutschland" },
  { "name": "SIGNAL IDUNA Lebensversicherung AG", "email": "info@signal-iduna.de", "address": "Joseph-Scherer-Straße 3, 44139 Dortmund, Deutschland" },
  { "name": "Skandia Lebensversicherung Aktiengesellschaft", "email": "service@ska-lv.de", "address": "Dornhofstraße 36, 63263 Neu-Isenburg, Deutschland" },
  { "name": "Sparkassen-Versicherung Sachsen Lebensversicherung Aktiengesellschaft", "email": "service@sv-sachsen.de", "address": "An der Flutrinne 12, 1139 Dresden, Deutschland" },
  { "name": "Stuttgarter Lebensversicherung a.G.", "email": "info@stuttgarter.de", "address": "Rotebühlstraße 120, 70197 Stuttgart, Deutschland" },
  { "name": "SV SparkassenVersicherung Lebensversicherung Aktiengesellschaft", "email": "service@sparkassenversicherung.de", "address": "Löwentorstraße 65, 70376 Stuttgart, Deutschland" },
  { "name": "Swiss Life Lebensversicherung SE", "email": "info@swisslife.de", "address": "Zeppelinstraße 1, 85748 Garching b. München, Deutschland" },
  { "name": "TARGO Lebensversicherung AG", "email": "info@targoversicherung.de", "address": "ProACTIV-Platz 1, 40721 Hilden, Deutschland" },
  { "name": "uniVersa Lebensversicherung a.G.", "email": "service@universa.de", "address": "Sulzbacher Straße 1 - 7, 90489 Nürnberg, Deutschland" },
  { "name": "VEREINIGTE POSTVERSICHERUNG VVaG", "email": "info@vpv.de", "address": "Mittlerer Pfad 19, 70499 Stuttgart, Deutschland" },
  { "name": "Versicherer im Raum der Kirchen Lebensversicherung AG", "email": "info@vrk.de", "address": "Doktorweg 2-4, 32756 Detmold, Deutschland" },
  { "name": "Victoria Lebensversicherung Aktiengesellschaft", "email": "info@ergo.de", "address": "ERGO-Platz 1, 40477 Düsseldorf, Deutschland" },
  { "name": "Volkswohl-Bund Lebensversicherung a.G.", "email": "info@volkswohl-bund.de", "address": "Südwall 37-41, 44137 Dortmund, Deutschland" },
  { "name": "VPV Lebensversicherungs-Aktiengesellschaft", "email": "info@vpv.de", "address": "Mittlerer Pfad 19, 70499 Stuttgart, Deutschland" },
  { "name": "WGV-Lebensversicherung AG", "email": "lv@wgv.de", "address": "Tübinger Straße 55, 70178 Stuttgart, Deutschland" },
  { "name": "WWK Lebensversicherung auf Gegenseitigkeit", "email": "info@wwk.de", "address": "Marsstraße 37, 80335 München, Deutschland" },
  { "name": "Württembergische Lebensversicherung Aktiengesellschaft", "email": "info@wuerttembergische.de", "address": "W+W-Platz 1, 70806 Kornwestheim, Deutschland" },
  { "name": "Zurich Deutscher Herold Lebensversicherung Aktiengesellschaft", "email": "service@zurich.de", "address": "Deutzer Allee 1, 50679 Köln, Deutschland" },
  { "name": "Zurich Life Legacy Versicherung AG (Deutschland)", "email": "service@zurich.de", "address": "Deutzer Allee 1, 50679 Köln, Deutschland" },
  { "name": "Öffentliche Lebensversicherung Sachsen-Anhalt", "email": "service.magdeburg@oesa.de", "address": "Am Alten Theater 7, 39104 Magdeburg, Deutschland" }
]

